name: publish Vue Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install
        run: npm install

      - name: Build storybook
        run: npm run build-storybook

      - name: Copy storybook
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 rm s3://front-farm-storybook --recursive \
          aws s3 cp \
            --recursive \
            --region us-east-1 \
            ./storybook-static s3://front-farm-storybook/

  #publish-gpr:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: actions/setup-node@v1
  #      with:
  #        node-version: 12
  #        registry-url: https://npm.pkg.github.com/
  #        scope: '@windix'
  #    - run: npm install
  #    - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
  #    - run: npm run build
  #    - run: git push --tags && git push
  #    - run: npm publish
  #      env:
  #        NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}